version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build steps...
      - npm run lint
      - npm run test
#   build:
#     commands:
#       - echo Building the application...
#       - npm run build
#   post_build:
#     commands:
#       - echo Post-build steps...
#       - echo Build completed on `date`
# artifacts:
#   files:
#     - "**/*"
#   discard-paths: yes
#   base-directory: dist
# cache:
#   paths:
#     - "node_modules/**/*"
# # artifacts:
# #   files: $CONTAINER_NAME.json
